# -*- coding: utf-8 -*-
"""prioritize problems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOSM3zMopg0sZcBb2chT0ts-SRReiHhg
"""

import math


def compute_user_rating(solved_problems):
    """
    solved_problems: list of dicts
        [{"rating": int}, ...]

    Returns:
        average rating of solved problems
    """

    if not solved_problems:
        return 1200  # fallback (neutral level)

    total = sum(p["rating"] for p in solved_problems)
    return total / len(solved_problems)


def prioritize_problems(
    problems,
    solved_problems,
    user_tag_strength,
    neighbor_tag_strength,
    C=250,
    alpha=0.6,
    beta=0.4,
    min_prob=0.25,
    max_prob=0.85
):
    """
    problems: candidate problems from your teammate
    solved_problems: problems user already solved (to compute rating)
    user_tag_strength: {tag: strength}
    neighbor_tag_strength: {tag: avg strength}

    Returns ranked problems
    """

    # -----------------------------
    # Step 0: Compute user rating
    # -----------------------------
    user_rating = compute_user_rating(solved_problems)

    # -----------------------------
    # Step 1: Normalize CF scores
    # -----------------------------
    max_score = max(p["problem_score"] for p in problems) or 1.0

    ranked = []

    for p in problems:
        tags = p["tags"]
        rating = p["rating"]

        # -----------------------------
        # Step 2: Success Probability
        # -----------------------------

        # Normalize CF score to [0,1]
        cf_norm = p["problem_score"] / max_score

        # Difference between problem difficulty and user level
        rating_diff = abs(rating - user_rating)

        # Convert difference → smooth difficulty score
        difficulty = math.exp(-rating_diff / C)

        # Final success probability
        success_prob = cf_norm * difficulty

        # -----------------------------
        # Step 3: Weakness Boost
        # -----------------------------
        contrast_values = []

        for tag in tags:
            # User strength (default 0.5 if missing)
            user_strength = user_tag_strength.get(tag, 0.5)

            # Neighbor strength
            neighbor_strength = neighbor_tag_strength.get(tag, 0.5)

            # User weakness
            weak_u = 1 - user_strength

            # Contrast idea
            contrast = weak_u * neighbor_strength

            contrast_values.append(contrast)

        # Average over all tags in problem
        if contrast_values:
            weakness_boost = sum(contrast_values) / len(contrast_values)
        else:
            weakness_boost = 0

        # -----------------------------
        # Step 4: Filter bad problems
        # -----------------------------
        if success_prob < min_prob or success_prob > max_prob:
            continue

        # -----------------------------
        # Step 5: Final Score
        # -----------------------------
        final_score = alpha * success_prob + beta * weakness_boost

        ranked.append({
            "id": p["id"],
            "rating": rating,
            "tags": tags,
            "success_prob": round(success_prob, 4),
            "weakness_boost": round(weakness_boost, 4),
            "final_score": round(final_score, 4)
        })

    # -----------------------------
    # Step 6: Sort
    # -----------------------------
    ranked.sort(
        key=lambda x: (x["final_score"], x["weakness_boost"]),
        reverse=True
    )

    return ranked