# -*- coding: utf-8 -*-
"""Find Unsolved Problems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGbwK6aUx7z6sTxlE_28MAHekNFVjROo
"""

def find_unsolved_problems(target_user_solved, neighbors, problem_metadata, limit=None):
    problem_scores = {}

    #  Step 1: iterate over nearest users
    for neighbor in neighbors:
        weight = neighbor["weight"]  # already similarity (higher = better)

        for problem_id in neighbor["solved_problems"]:

            #  Step 2: filter solved problems
            if problem_id in target_user_solved:
                continue

            #  Step 3: accumulate score
            if problem_id not in problem_scores:
                problem_scores[problem_id] = 0

            # higher weight + repetition = higher score automatically
            problem_scores[problem_id] += weight

    #  Step 4: build full objects
    results = []
    for problem_id, score in problem_scores.items():
        if problem_id not in problem_metadata:
            continue

        problem_info = problem_metadata[problem_id]

        results.append({
            "problem_id": problem_id,
            "tags": problem_info["tags"],
            "difficulty": problem_info["difficulty"],
            "score": score
        })

    # Step 5: sort by importance (descending)
    results.sort(key=lambda x: x["score"], reverse=True)

    #  Step 6: optional limit (kept in structure only)
    if limit is not None:
        results = results[:limit]

    return results